@host = http://localhost:5214

GET  {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNTMzNDgwMy02YjU1LTQzYzQtYTBiNS0wMWVmNWYxZGVkZGIiLCJnaXZlbl9uYW1lIjoiVGltIiwiZmFtaWx5X25hbWUiOiJDb3JleSIsImp0aSI6ImU1ZTJiODg4LTAxNmMtNGUwMC1iOTJjLTYwODkxYzI4NGU1YSIsImV4cCI6MTcwNTgwNjIyOSwiaXNzIjoiRmFzdEJ1YmJlckRpbm5lciIsImF1ZCI6IkZhc3RCdWJiZXJEaW5uZXIifQ.qj_Zj81dGOFEYgTgzmcKgtlAI-XArsIZE47ZIhQqne8