@host = http://localhost:5214

POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "timcorey@ms.net",
    "password": "someCode"
}

### 

POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "amichai@ms.net",
    "password": "somePass"
}