@host = http://localhost:5214

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Tim",
    "lastName": "Corey",
    "email": "timcorey@ms.net",
    "password": "someCode"
}